=== aldl1910/lenguaje/Tema4/XML/Actividad2.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Actividad2.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE concesionario SYSTEM "Actividad2.dtd">

    <concesionario>
    ...
    </concesionario>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT concesionario (coche)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT coche (codigo|matricula|marca|modelo)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codigo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT matricula (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT marca (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT modelo (potencia|plazas|numPuertas)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT potencia (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plazas (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT numPuertas (#PCDATA)>

=== aldl1910/lenguaje/Tema4/XML/Actividad2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DefiniciÃ³n del documento XML-->
<!DOCTYPE concesionario SYSTEM "Actividad2.dtd">
<concesionario>
    <coche> 
        <codigo>648789745645a</codigo>
        <matricula>6584CA</matricula>
        <marca>Ford</marca>
        <modelo>
            <potencia>455</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
        </modelo>       
    </coche>
    <coche> 
        <codigo>756489124672b</codigo>
        <matricula>8765MA</matricula>
        <marca>Ford</marca>
        <modelo>
            <potencia>450</potencia>
            <plazas>5</plazas>
            <numPuertas>4</numPuertas>
        </modelo>       
    </coche> 
    <coche> 
        <codigo>786489752482c</codigo>
        <matricula>7865M</matricula>
        <marca>Ford</marca>
        <modelo>
            <potencia>500</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
        </modelo>       
    </coche>
</concesionario>
